from . import Tuni_menu
from . import Tuni_sale_wizard
from . import Tuni_sale
from . import Tuni_finance
from . import Tuni_menu_segment_report
from . import Tuni_menu_milk_report
from . import Tuni_purchase
from . import Tuni_rent_report
from . import Tuni_employee
from . import Tuni_salary
from . import Tuni_shift
from . import Tuni_attendance
from . import Tuni_attendance_wizard
from . import Tuni_shift_wizard
from . import Tuni_order
from . import Tuni_order_line
from . import Tuni_purchase_wizard
from . import Tuni_order_wizard
from . import Tuni_customer
from . import Tuni_promotion
from . import Tuni_promotion_gift
from . import Tuni_chat_support
from . import Tuni_inventory
from . import Tuni_chart